name: Continuos Integration
on:
  pull_request:
    branches: [staging]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Test applicaiton
        run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/handytec-webapp:${{steps.vars.outputs.tag}}

      - name: Push the tagged Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/handytec-webapp:${{steps.vars.outputs.tag}}
