name: CI/CD
on:
  pull_request:
    branches: [staging]
jobs:
  #  test:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v2
  #
  #      - name: Install dependencies
  #        run: npm install
  #
  #      - name: Test applicaiton
  #        run: npm run test
  #  approve:
  #    needs: test
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v2
  #
  #      - name: Approve pull request
  #        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
  #        with:
  #          repo-token: "${{ secrets.GITHUB_TOKEN }}"
  #          event: APPROVE
  #          body: "Thank you dependabot 🎊"
  deploy:
    # needs: approve
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build and push
        env:
          ENVIRONMENT: staging
          PORT: 3000
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web

      - name: Release
        env:
          ENVIRONMENT: staging
          PORT: 3000
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
